-- =============================================================================
-- Golden preneur Database Import Script — Speakers & Partners
-- Run this script in phpMyAdmin or MySQL console on your live Hostinger server.
-- =============================================================================

USE `gree_goldenpreneur_db`; -- Adjust database name if different on live server

-- Modify pass_type column to support custom delegate pass values in event registrations
ALTER TABLE `event_registrations` MODIFY COLUMN `pass_type` VARCHAR(100) NOT NULL DEFAULT 'general';

-- Clean existing data to prevent duplicates if script is run multiple times
DELETE FROM `jury`;
DELETE FROM `partners`;
DELETE FROM `sponsors`;

-- 1. Insert Speakers & Jury
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Achal Rangaswamy', 'Business Coach & Author', 'Peers Global', '["Coach","Author","Speaker"]', '/uploads/nominations/Achal Rangaswamy.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Aditya Jhunjhunwala', 'Co-Founder, ADMC & Business Coach', 'ADMC', '["Coach","Speaker"]', '/uploads/nominations/Aditya Jhunjhunwala.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Ajay Thakur', 'CEO & Managing Partner', 'TGI SME Capital Advisors LLP', '["Finance","Speaker"]', '/uploads/nominations/Ajay Thakur.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Binjan Sheth', 'Founder, Coding and More & Director', 'Thinkgreen Envirotech Pvt Ltd', '["Envirotech","Education","Speaker"]', '/uploads/nominations/Binjan Sheth.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('CA Shubham Maloo', 'Chartered Accountant & Founder', 'Shubham Maloo & Co.', '["Finance","Consultant","Speaker"]', '/uploads/nominations/CA Shubham Maloo.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Chandrakant Salunkhe', 'Founder & President', 'SME Chamber of India', '["SME Leader","President","Speaker"]', '/uploads/nominations/Chandrakant Salunkhe.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr Parimal Merchant', 'Director, Global FMB Program', 'SP Jain School of Global Management', '["Academician","Director","Speaker"]', '/uploads/nominations/Dr Parimal Merchant.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr. Krishna Singh Arya', 'SDG Champion, Mentor & Academician', 'World Leader Summit', '["SDG Champion","Mentor","Speaker"]', '/uploads/nominations/Dr. Krishna Singh Arya.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Jagdish Vishwakarma', 'MoS for MSME, Cooperation & Cottage Industries', 'Government of Gujarat', '["Minister","MSME Leader","Speaker"]', '/uploads/nominations/Jagdish Vishwakarma.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Kuldipsingh Kaler', 'Creative Head – Marketing', 'Tea Post', '["Marketing","Influencer","Speaker"]', '/uploads/nominations/Kuldipsingh Kaler.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Madhu Menon', 'Director, Anala Outdoors & Sattva Vikas School', 'Anala Outdoors', '["Biodiversity","Director","Speaker"]', '/uploads/nominations/Madhu Menon.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Moloy Chakravorty', 'Founder & Managing Director', 'Beyond Red Ocean Consulting', '["Coach","Consultant","Speaker"]', '/uploads/nominations/Moloy Chakravorty.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Nayan Mehta', 'Chief Financial Officer', 'BSE (Bombay Stock Exchange) Limited', '["Finance","CFO","Speaker"]', '/uploads/nominations/Nayan Mehta.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Pabiben Rabari', 'Founder', 'Pabiben.com', '["Artisan","Entrepreneur","Speaker"]', '/uploads/nominations/Pabiben Rabari.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('R. Gopinath Rao', 'IEDS, Deputy Director, MSME Development Institute', 'Government of India', '["Government","MSME Director","Speaker"]', '/uploads/nominations/R. Gopinath Rao.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Ramkumar Seshu', 'Business Coach, Mentor & Founder', 'Seshu Consulting', '["Coach","Mentor","Speaker"]', '/uploads/nominations/Ramkumar Seshu.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Shiv Khera', 'Author, Educator & Motivational Speaker', 'Qualified Learning Systems', '["Author","Speaker","Jury"]', '/uploads/nominations/Shiv Khera.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Shraddha Musale', 'Founder, FutureTayari / Actor & Presence Coach', 'FutureTayari', '["Founder","Actor","Coach","Speaker"]', '/uploads/nominations/Shraddha Musale.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Suresh Mansharamani', 'Founder, Tajurba Business Network & OKR Expert', 'Tajurba Business Network', '["Coach","Founder","Speaker","Jury"]', '/uploads/nominations/Suresh Mansharamani.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Tanvvi Rathod', 'Founder, Maisson By Tanvvi Rathod / Mentorship Expert', 'Maisson By Tanvvi Rathod', '["Mentor","Trainer","Speaker"]', '/uploads/nominations/Tanvvi Rathod.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Vijay Kalantri', 'President, AIAI & Chairman', 'MVIRDC World Trade Center Mumbai', '["Industry Leader","President","Speaker"]', '/uploads/nominations/Vijay  Kalantri.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Sanjay Raval', 'Author, Motivational Speaker & Entrepreneur', 'Sanjay Raval Seminars', '["Author","Speaker","Entrepreneur"]', '/uploads/nominations/sanjay raval.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Anil Mulchandani', 'Editorial & writing , social entrepreneurship, event curator, food industry, tourism', '', '["Writer","Author","Speaker"]', '/uploads/nominations/Anil Mulchandani.jpg', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Devang Brahmbhatt', 'Founder', 'Nature coat', '["Entrepreneur","Speaker"]', '/uploads/nominations/Devang Brahmbhatt.jpg', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr. Pravin Parmar', 'Promoter & Founder', 'Peers Global', '["Founder","President","Speaker","Jury"]', '/uploads/nominations/Dr. Pravin Parmar.jpg', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr. Sachin Shigwan', 'The Solar Man of India', '', '["Solar Tech","Rural Electrification","Speaker","Jury"]', '/uploads/nominations/Dr. Sachin Shigwan.jpg', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Dr. Akshay Kumar', 'Founder & Director', 'BroGhar Realty pvt. Ltd.', '["Real Estate","Entrepreneur","Speaker"]', '/uploads/nominations/Dr. Akshay kumar.png', 'linear-gradient(160deg,#e52d27,#7303c0)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Itesh Lakum', 'Founder', 'Sun Wave Energy', '["Organic Farming","Speaker"]', '/uploads/nominations/Itesh Lakum.jpg', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Nilesh Priyadarshi', 'Founder & CEO', 'Kaarigar Clinic', '["Social Entrepreneur","Rural Development","Speaker","Jury"]', '/uploads/nominations/Nilesh Priyadarshi.jpg', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Niraj Shah', 'District Executive Director & Global Advisor', '', '["Advisor","Speaker","Jury"]', '/uploads/nominations/Niraj Shah.jpg', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Samir Sinha', 'Founder & MD', 'Savvy Group', '["Conservation","Forestry","Speaker","Jury"]', '/uploads/nominations/Samir Sinha.jpg', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Vinod Malviya', 'Co Founder', 'Shubham Aquavitro Pvt Ltd', '["Wastewater Engineering","Green Building","Speaker"]', '/uploads/nominations/Vinod Malviya.jpg', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Phani Trivedi', 'Founder', 'WeEngage Global Foundation & IGBC Accredited Professional', '["Founder","Sustainability","Speaker"]', '/uploads/nominations/Phani Trivedi.jpg', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Unmesh Dixit', 'Executive Director', 'AMA', '["Executive Director","Mentor","Speaker"]', '/uploads/nominations/Unmesh Dixit.jpg', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `jury` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Rohan Shah', 'Design Thinking & Digital Transformation expert, Founder', 'Founders+', '["Design Thinking","Digital Transformation","Founder","Speaker"]', '/uploads/nominations/Rohan Shah.jpg', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);



-- 2. Insert Partners
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('0 West', 'Sustainability Partner', '0 West Sustainability Solutions', '["Zero Waste","Sustainability"]', '/uploads/nominations/0 West.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('123 Eco-Solutions', 'Support Partner', '123 Group', '["Eco-Solutions","Green Energy"]', '/uploads/nominations/123.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Agroyis', 'Agro-Tech Partner', 'Agroyis Agri Solutions', '["Agro-Tech","Organic Farming"]', '/uploads/nominations/Agroyis.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('All About', 'Branding & Marketing Partner', 'All About Marketing Consultancy', '["Branding","Marketing"]', '/uploads/nominations/All About.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Body Tales', 'Organic Wellness Partner', 'The Body Tales Skin Care', '["Organic Wellness","Cosmetics"]', '/uploads/nominations/Body Tales.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Concepts Green', 'Green Consultancy Partner', 'Concepts Green Consultancy', '["Green Tech","Consulting"]', '/uploads/nominations/Concepts. green.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('DevX', 'Ecosystem & Incubation Partner', 'DevX Co-Working & Innovation', '["Incubation","Startups","Co-working"]', '/uploads/nominations/DevX.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Glam Greens Herbal Care', 'Natural Wellness Partner', 'Glam Greens Herbal Care Products', '["Herbal Care","Organic Products"]', '/uploads/nominations/Glam Greens Herbal Care.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Gyan Enviro', 'Environmental Consultant Partner', 'Gyan Enviro Consultants', '["Waste Management","Audit","Environmental"]', '/uploads/nominations/Gyan Enviro.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('IBS', 'Education & Knowledge Partner', 'ICFAI Business School', '["Education","Mentorship","Business School"]', '/uploads/nominations/IBS.png', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('IDBI Bank', 'Banking Partner', 'IDBI Bank Limited', '["Banking","Finance","SME Loans"]', '/uploads/nominations/IDBI Bank.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Navitas Green Solutions Pvt. Ltd.', 'Solar Technology Partner', 'Navitas Solar', '["Solar Energy","Renewables","Manufacturing"]', '/uploads/nominations/Navitas Green Solutions Pvt. Ltd.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Rupee Boss', 'Financial Services Partner', 'Rupeeboss Financial Services Pvt. Ltd.', '["Financial Services","Loans","SME Growth"]', '/uploads/nominations/Rupee Boss.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `partners` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('WAACAB', 'Solar Energy Solutions Partner', 'WAACAB Solar Technology', '["Solar Tech","Renewables"]', '/uploads/nominations/WAACAB.png', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);

-- 3. Insert Sponsors
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Broghar Realty', 'Title Sponsor', 'Broghar Realty', '["Title Sponsor"]', '/uploads/nominations/Broghar Realty.png', 'linear-gradient(160deg,#e52d27,#7303c0)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Aerolam', 'Platinum Sponsor', 'Aerolam', '["Platinum Sponsor"]', '/uploads/nominations/Aerolam.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Sun Wave Energy', 'Powered By', 'Sun Wave Energy', '["Powered By"]', '/uploads/nominations/Sun Wave Energy (Powered By).jpg', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Armorfire', 'Powered By', 'Armorfire', '["Powered By"]', '/uploads/nominations/Armorfire.jpeg', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('CampusDean', 'Gold Sponsor', 'CampusDean', '["Gold Sponsor"]', '/uploads/nominations/CampusDean(Gold Sponsor).jpg', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('CampusJobs.ai', 'Gold Sponsor', 'CampusJobs.ai', '["Gold Sponsor"]', '/uploads/nominations/CampusJobs.ai (Gold Sponsor).jpg', 'linear-gradient(160deg,#4a8a90,#2d6a70)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Nature Coat', 'Gold Sponsor', 'Nature Coat', '["Gold Sponsor"]', '/uploads/nominations/Nature Coat(Gold Sponsor).jpg', 'linear-gradient(160deg,#5a8a70,#3a6a52)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('CEED', 'Associate Partner', 'CEED', '["Associate Partner"]', '/uploads/nominations/CEED (Associate Partner).jpg', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Fempreneur', 'Associate Partner', 'Fempreneur', '["Associate Partner"]', '/uploads/nominations/Fempreneur.png', 'linear-gradient(160deg,#8a3a9a,#5a1a7a)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('1 Million', 'Organized by', '1 Million', '["Organized by"]', '/uploads/nominations/1 Million.png', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Peers Global', 'Organized by', 'Peers Global', '["Organized by"]', '/uploads/nominations/Peers Global.png', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Aequitas Infotech', 'Technology Partner', 'Aequitas Infotech', '["Technology Partner"]', '/uploads/nominations/AequitasInfotech.png', 'linear-gradient(160deg,#1e3c72,#2a5298)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('VyapaarJagat.com', 'Media Partner', 'VyapaarJagat.com', '["Media Partner"]', '/uploads/nominations/VyapaarJagat.com.png', 'linear-gradient(160deg,#2a3a7a,#1a2a6a)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Porcious', 'Platinum Sponsor', 'Porcious', '["Platinum Sponsor"]', '/uploads/nominations/Porcious.jpg', 'linear-gradient(160deg,#7a9a60,#5a7a44)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('TVM', 'PR Partner', 'TVM', '["PR Partner"]', '/uploads/nominations/TVM.jpg', 'linear-gradient(160deg,#1e3c72,#2a5298)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Shaadi Vows', 'event managed by', 'Shaadi Vows', '["event managed by"]', '/uploads/nominations/Shaadi Vows.jpg', 'linear-gradient(160deg,#7303c0,#ec38bc)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Wide Reach', 'Digital Display Partner', 'Wide Reach', '["Digital Display Partner"]', '/uploads/nominations/Wide Reach.jpg', 'linear-gradient(160deg,#1e3c72,#2a5298)', 1);
INSERT INTO `sponsors` (`name`, `role`, `org`, `tags`, `photo_url`, `bg_gradient`, `is_published`) VALUES ('Zybra', 'Gold Sponsor', 'Zybra', '["Gold Sponsor"]', '/uploads/nominations/Zybra.jpg', 'linear-gradient(160deg,#5a9a6a,#3d7a50)', 1);

